### ISSUE TITLE
Game crash when jvm loaded on playing ogg

### ISSUE THREAD

**Issue by neoedmund** [beyond-all-reason/spring#260]
1. happen on recent engine?
2. happen when using java AI bot eg. `NullOOJavaAI`
3. adding `if(1)return;` to 1st line of `void CSoundSource::PlayStream(IAudioChannel* channel, const std::string& file, float volume)` will make game run OK.
4. without java AI bot, no need to change engine source, and game is OK.

guessing: fail to play ogg stuff but caught by jvm?

log:

```

[t=00:00:20.459564][f=0000031] Loaded atmosphere CEGs config for map: DSDR 4.0
An irrecoverable stack overflow has occurred.
[t=00:00:23.159680][f=0000112] [CrashHandler] Error: Segmentation fault in Spring 105.1.1-930-g9c7558c BAR105
[t=00:00:23.159713][f=0000112] [CrashHandler] Error: Halted Stacktrace for Spring 105.1.1-930-g9c7558c BAR105 (SIGSEGV) using libunwind:
Please check if any of your loaded .so files has enabled executable stack (see man page execstack(8))
[t=00:00:23.412006][f=0000112] [CrashHandler] Error:   <00>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907  CrashHandler::HaltedStacktrace(siginfo_t*, ucontext_t*, char const*)
[t=00:00:23.412030][f=0000112] [CrashHandler] Error: [00]                                                                           0x694bf4  /xxxx/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907
[t=00:00:23.412035][f=0000112] [CrashHandler] Error:   <01>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935  CrashHandler::CleanupStacktrace(int)
[t=00:00:23.412039][f=0000112] [CrashHandler] Error:   <01>                                                                         0x695263  /xxxx/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935
[t=00:00:23.412044][f=0000112] [CrashHandler] Error:   <01>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997  CrashHandler::HandleSignal(int, siginfo_t*, void*)
[t=00:00:23.412048][f=0000112] [CrashHandler] Error: [01]                                                                           0x695263  /xxxx/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997
[t=00:00:23.412053][f=0000112] [CrashHandler] Error:   <02>                     /opt/jdk-17/lib/server/libjvm.so(+0xcb8949) [0x7f6843cb8949]  PosixSignals::chained_handler(int, siginfo*, void*) [clone .part.0]
[t=00:00:23.412057][f=0000112] [CrashHandler] Error: [02]                                                                           0xcb8949  ??:?
[t=00:00:23.412061][f=0000112] [CrashHandler] Error:   <03> /opt/jdk-17/lib/server/libjvm.so(JVM_handle_linux_signal+0x256) [0x7f6843cb93a6]  JVM_handle_linux_signal
[t=00:00:23.412065][f=0000112] [CrashHandler] Error:   <03>                                                                         0xcb93a6  ??:?
[t=00:00:23.412069][f=0000112] [CrashHandler] Error:   <04>                 /lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7f69e72a6140]  __restore_rt
[t=00:00:23.412073][f=0000112] [CrashHandler] Error:   <04>                                                                          0x14140  ??:?
[t=00:00:23.412078][f=0000112] [CrashHandler] Error:   <05>                      /lib/x86_64-linux-gnu/libc.so.6(+0x163077) [0x7f69e65f2077]  __nss_database_lookup
[t=00:00:23.412082][f=0000112] [CrashHandler] Error: [05]                                                                           0x163077  ??:?
[t=00:00:23.412087][f=0000112] [CrashHandler] Error:   <06>                 ./springrts/spring-bar105/rts/System/Sound/OpenAL/OggStream.h:16  COggStream::operator=(COggStream const&)
[t=00:00:23.412091][f=0000112] [CrashHandler] Error:   <06>                                                                         0x6f14ee  /xxxx/spring-bar105/rts/System/Sound/OpenAL/OggStream.h:16
[t=00:00:23.412105][f=0000112] [CrashHandler] Error:   <06>            ./springrts/spring-bar105/rts/System/Sound/OpenAL/SoundSource.cpp:293  CSoundSource::PlayStream(IAudioChannel*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)
[t=00:00:23.412110][f=0000112] [CrashHandler] Error: [06]                                                                           0x6f14ee  /xxxx/spring-bar105/rts/System/Sound/OpenAL/SoundSource.cpp:293
[t=00:00:23.412115][f=0000112] [CrashHandler] Error:   <07>           ./springrts/spring-bar105/rts/System/Sound/OpenAL/AudioChannel.cpp:194  AudioChannel::StreamPlay(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, bool)
[t=00:00:23.412120][f=0000112] [CrashHandler] Error: [07]                                                                           0x6e2e74  /xxxx/spring-bar105/rts/System/Sound/OpenAL/AudioChannel.cpp:194
[t=00:00:23.412124][f=0000112] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:187  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const
[t=00:00:23.412129][f=0000112] [CrashHandler] Error:   <08>                                                                         0x394afb  /usr/include/c++/10/bits/basic_string.h:187
[t=00:00:23.412134][f=0000112] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:222  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
[t=00:00:23.412138][f=0000112] [CrashHandler] Error:   <08>                                                                         0x394afb  /usr/include/c++/10/bits/basic_string.h:222
[t=00:00:23.412143][f=0000112] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:231  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
[t=00:00:23.412148][f=0000112] [CrashHandler] Error:   <08>                                                                         0x394afb  /usr/include/c++/10/bits/basic_string.h:231
[t=00:00:23.412153][f=0000112] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:658  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
[t=00:00:23.412157][f=0000112] [CrashHandler] Error:   <08>                                                                         0x394afb  /usr/include/c++/10/bits/basic_string.h:658
[t=00:00:23.412162][f=0000112] [CrashHandler] Error:   <08>                        ./springrts/spring-bar105/rts/Lua/LuaUnsyncedCtrl.cpp:600  LuaUnsyncedCtrl::PlaySoundStream(lua_State*)
[t=00:00:23.412167][f=0000112] [CrashHandler] Error: [08]                                                                           0x394afb  /xxxx/spring-bar105/rts/Lua/LuaUnsyncedCtrl.cpp:600
[t=00:00:23.412171][f=0000112] [CrashHandler] Error:   <09>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:321  luaD_precall(lua_State*, lua_TValue*, int)
[t=00:00:23.412176][f=0000112] [CrashHandler] Error: [09]                                                                           0x719a70  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:321
[t=00:00:23.412181][f=0000112] [CrashHandler] Error:   <10>                            ./springrts/spring-bar105/rts/lib/lua/src/lvm.cpp:620  luaV_execute(lua_State*, int)
[t=00:00:23.412185][f=0000112] [CrashHandler] Error: [10]                                                                           0x728e54  /xxxx/spring-bar105/rts/lib/lua/src/lvm.cpp:620
[t=00:00:23.412190][f=0000112] [CrashHandler] Error:   <11>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:378  luaD_call(lua_State*, lua_TValue*, int)
[t=00:00:23.412195][f=0000112] [CrashHandler] Error: [11]                                                                           0x719ed5  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:378
[t=00:00:23.412202][f=0000112] [CrashHandler] Error:   <12>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:119  luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*)
[t=00:00:23.412206][f=0000112] [CrashHandler] Error: [12]                                                                           0x7193fe  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:119
[t=00:00:23.412211][f=0000112] [CrashHandler] Error:   <13>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:464  luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long)
[t=00:00:23.412215][f=0000112] [CrashHandler] Error: [13]                                                                           0x71a1b0  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:464
[t=00:00:23.412220][f=0000112] [CrashHandler] Error:   <14>                           ./springrts/spring-bar105/rts/lib/lua/src/lapi.cpp:833  lua_pcall(lua_State*, int, int, int)
[t=00:00:23.412225][f=0000112] [CrashHandler] Error: [14]                                                                           0x713a25  /xxxx/spring-bar105/rts/lib/lua/src/lapi.cpp:833
[t=00:00:23.412229][f=0000112] [CrashHandler] Error:   <15>                       ./springrts/spring-bar105/rts/lib/lua/src/lbaselib.cpp:378  luaB_pcall(lua_State*)
[t=00:00:23.412234][f=0000112] [CrashHandler] Error: [15]                                                                           0x715a18  /xxxx/spring-bar105/rts/lib/lua/src/lbaselib.cpp:378
[t=00:00:23.412239][f=0000112] [CrashHandler] Error:   <16>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:321  luaD_precall(lua_State*, lua_TValue*, int)
[t=00:00:23.412243][f=0000112] [CrashHandler] Error: [16]                                                                           0x719a70  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:321
[t=00:00:23.412248][f=0000112] [CrashHandler] Error:   <17>                            ./springrts/spring-bar105/rts/lib/lua/src/lvm.cpp:620  luaV_execute(lua_State*, int)
[t=00:00:23.412252][f=0000112] [CrashHandler] Error: [17]                                                                           0x728e54  /xxxx/spring-bar105/rts/lib/lua/src/lvm.cpp:620
[t=00:00:23.412257][f=0000112] [CrashHandler] Error:   <18>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:378  luaD_call(lua_State*, lua_TValue*, int)
[t=00:00:23.412262][f=0000112] [CrashHandler] Error: [18]                                                                           0x719ed5  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:378
[t=00:00:23.412266][f=0000112] [CrashHandler] Error:   <19>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:119  luaD_rawrunprotected(lua_State*, void (*)(lua_State*, void*), void*)
[t=00:00:23.412271][f=0000112] [CrashHandler] Error: [19]                                                                           0x7193fe  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:119
[t=00:00:23.412275][f=0000112] [CrashHandler] Error:   <20>                            ./springrts/spring-bar105/rts/lib/lua/src/ldo.cpp:464  luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long)
[t=00:00:23.412280][f=0000112] [CrashHandler] Error: [20]                                                                           0x71a1b0  /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:464
[t=00:00:23.412284][f=0000112] [CrashHandler] Error:   <21>                           ./springrts/spring-bar105/rts/lib/lua/src/lapi.cpp:833  lua_pcall(lua_State*, int, int, int)
[t=00:00:23.412289][f=0000112] [CrashHandler] Error: [21]                                                                           0x713a25  /xxxx/spring-bar105/rts/lib/lua/src/lapi.cpp:833
[t=00:00:23.412296][f=0000112] [CrashHandler] Error:   <22>                              ./springrts/spring-bar105/rts/Lua/LuaHandle.cpp:329  CLuaHandle::RunCallInTraceback(lua_State*, LuaHashString const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, int, int, bool)
[t=00:00:23.412301][f=0000112] [CrashHandler] Error:   <22>                                                                         0x2d73e7  /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:329
[t=00:00:23.412306][f=0000112] [CrashHandler] Error:   <22>                              ./springrts/spring-bar105/rts/Lua/LuaHandle.cpp:413  CLuaHandle::RunCallInTraceback(lua_State*, LuaHashString const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int, int, int, bool)
[t=00:00:23.412310][f=0000112] [CrashHandler] Error: [22]                                                                           0x2d73e7  /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:413
[t=00:00:23.412315][f=0000112] [CrashHandler] Error:   <23>                              ./springrts/spring-bar105/rts/Lua/LuaHandle.cpp:423  CLuaHandle::RunCallInTraceback(lua_State*, LuaHashString const&, int, int, int, bool)
[t=00:00:23.412320][f=0000112] [CrashHandler] Error: [23]                                                                           0x2d7a98  /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:423
[t=00:00:23.412324][f=0000112] [CrashHandler] Error:   <24>                              ./springrts/spring-bar105/rts/Lua/LuaHandle.cpp:658  CLuaHandle::GameFrame(int)
[t=00:00:23.412329][f=0000112] [CrashHandler] Error: [24]                                                                           0x2e3d76  /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:658
[t=00:00:23.412333][f=0000112] [CrashHandler] Error:   <25>                       .../include/c++/10/bits/stl_vector.h:919 (discriminator 4)  std::vector<CEventClient*, std::allocator<CEventClient*> >::size() const
[t=00:00:23.412338][f=0000112] [CrashHandler] Error:   <25>                                                                         0x5ee460  /usr/include/c++/10/bits/stl_vector.h:919 (discriminator 4)
[t=00:00:23.412343][f=0000112] [CrashHandler] Error:   <25>      ./springrts/spring-bar105/rts/System/EventHandler.cpp:461 (discriminator 4)  void IterateEventClientList<std::vector<CEventClient*, std::allocator<CEventClient*> >, void (CEventClient::*)(int), int&>(std::vector<CEventClient*, std::allocator<CEventClient*> >&, void (CEventClient::* const&)(int), int&)
[t=00:00:23.412348][f=0000112] [CrashHandler] Error: [25]                                                                           0x5ee460  /xxxx/spring-bar105/rts/System/EventHandler.cpp:461 (discriminator 4)
[t=00:00:23.412352][f=0000112] [CrashHandler] Error:   <26>                        ./springrts/spring-bar105/rts/System/EventHandler.cpp:505  CEventHandler::GameFrame(int)
[t=00:00:23.412357][f=0000112] [CrashHandler] Error: [26]                                                                           0x5e7d20  /xxxx/spring-bar105/rts/System/EventHandler.cpp:505
[t=00:00:23.412361][f=0000112] [CrashHandler] Error:   <27>                                 ./springrts/spring-bar105/rts/Game/Game.cpp:1752  CGame::SimFrame()
[t=00:00:23.412366][f=0000112] [CrashHandler] Error: [27]                                                                           0x186ba2  /xxxx/spring-bar105/rts/Game/Game.cpp:1752
[t=00:00:23.412371][f=0000112] [CrashHandler] Error:   <28>                            ./springrts/spring-bar105/rts/Net/NetCommands.cpp:568  CGame::ClientReadNet()
[t=00:00:23.412375][f=0000112] [CrashHandler] Error: [28]                                                                           0x2b4960  /xxxx/spring-bar105/rts/Net/NetCommands.cpp:568
[t=00:00:23.412380][f=0000112] [CrashHandler] Error:   <29>                                        .../include/c++/10/bits/atomic_base.h:426  std::__atomic_base<bool>::load(std::memory_order) const
[t=00:00:23.412387][f=0000112] [CrashHandler] Error:   <29>                                                                         0x18d2d5  /usr/include/c++/10/bits/atomic_base.h:426
[t=00:00:23.412391][f=0000112] [CrashHandler] Error:   <29>                                                     .../include/c++/10/atomic:87  std::atomic<bool>::operator bool() const
[t=00:00:23.412396][f=0000112] [CrashHandler] Error:   <29>                                                                         0x18d2d5  /usr/include/c++/10/atomic:87
[t=00:00:23.412401][f=0000112] [CrashHandler] Error:   <29>                                 ./springrts/spring-bar105/rts/Game/Game.cpp:1210  CGame::Update()
[t=00:00:23.412405][f=0000112] [CrashHandler] Error: [29]                                                                           0x18d2d5  /xxxx/spring-bar105/rts/Game/Game.cpp:1210
[t=00:00:23.412410][f=0000112] [CrashHandler] Error:   <30>         ./springrts/spring-bar105/rts/System/SpringApp.cpp:806 (discriminator 2)  SpringApp::Update()
[t=00:00:23.412415][f=0000112] [CrashHandler] Error: [30]                                                                           0x61596d  /xxxx/spring-bar105/rts/System/SpringApp.cpp:806 (discriminator 2)
[t=00:00:23.412419][f=0000112] [CrashHandler] Error:   <31>                                        .../include/c++/10/bits/atomic_base.h:426  std::__atomic_base<bool>::load(std::memory_order) const
[t=00:00:23.412424][f=0000112] [CrashHandler] Error:   <31>                                                                         0x618bd8  /usr/include/c++/10/bits/atomic_base.h:426
[t=00:00:23.412429][f=0000112] [CrashHandler] Error:   <31>                                                     .../include/c++/10/atomic:87  std::atomic<bool>::operator bool() const
[t=00:00:23.412433][f=0000112] [CrashHandler] Error:   <31>                                                                         0x618bd8  /usr/include/c++/10/atomic:87
[t=00:00:23.412438][f=0000112] [CrashHandler] Error:   <31>                           ./springrts/spring-bar105/rts/System/SpringApp.cpp:845  SpringApp::Run()
[t=00:00:23.412442][f=0000112] [CrashHandler] Error: [31]                                                                           0x618bd8  /xxxx/spring-bar105/rts/System/SpringApp.cpp:845
[t=00:00:23.412447][f=0000112] [CrashHandler] Error:   <32>                                 ./springrts/spring-bar105/rts/System/Main.cpp:47  Run(int, char**)
[t=00:00:23.412452][f=0000112] [CrashHandler] Error: [32]                                                                           0x602983  /xxxx/spring-bar105/rts/System/Main.cpp:47
[t=00:00:23.412456][f=0000112] [CrashHandler] Error:   <33>         /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7f69e64b5d0a]  __libc_start_main
[t=00:00:23.412461][f=0000112] [CrashHandler] Error:   <33>                                                                          0x26d0a  ??:?
[t=00:00:23.412466][f=0000112] [CrashHandler] Error:   <34>                                         .../spring(_start+0x2a) [0x565509b7af8a]  _start
[t=00:00:23.412471][f=0000112] [CrashHandler] Error:   <34>                                                                         0x166f8a  ??:?
[t=00:00:23.412510][f=0000112] [WatchDog::DeregisterThread] deregistering controls for thread [main]
```

**Comment by lhog** [comment]
Ugh... Thanks for the report, though I'm afraid we have no one looking after Java AI interfaces.

As far as recent or not, the only tangible change to the sound system I can recall is https://github.com/beyond-all-reason/spring/commit/8f66c89f9551842bf769843db052000ee799c796 and it doesn't look related.

I'm not entirely sure how to proceed here, but as a first step can you check if any of the releases here: https://github.com/beyond-all-reason/spring/releases load the `NullOOJavaAI` succesfully (probably worth doing in a binary search like pattern). If such release is found we can at least guess what caused the issue.

**Comment by neoedmund** [comment]
I tested some tags(thanks for 24 core AMD CPU and ccache), it's not a recent bug. 
even  "spring_bar_{BAR105}105.1.1-475-gd112b9e" on "Sep 3, 2021" NG with same error.

I guess it's related with ogg on Linux.

But I still cannot explain why ogg not crash when jvm is not loaded.


Something it's  not likely related with java. when jvm is loaded, it will `JVM_handle_linux_signal` automatically. 
for example, on tag "105.0" on Jan 2, 2021 crash earlier on another error, with or without jvm loaded.

log withour jvm
```
[t=00:00:11.864290][f=-000001] [CrashHandler] Error: Segmentation fault in Spring 105.1.1-1-g922607f HEAD
[t=00:00:11.864304][f=-000001] [CrashHandler] Error: Halted Stacktrace for Spring 105.1.1-1-g922607f HEAD (SIGSEGV) using libunwind:
[t=00:00:11.873262][f=-000001] [CrashHandler] Error: This stacktrace indicates a problem with a skirmish AI.
[t=00:00:12.145616][f=-000001] [CrashHandler] Error:   <00>  ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907  CrashHandler::HaltedStacktrace(siginfo_t*, ucontext_t*, char const*)
[t=00:00:12.145638][f=-000001] [CrashHandler] Error: [00]                                                                    0x5830e4  /xxxx/springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907
[t=00:00:12.145642][f=-000001] [CrashHandler] Error:   <01>  ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935  CrashHandler::CleanupStacktrace(int)
[t=00:00:12.145645][f=-000001] [CrashHandler] Error:   <01>                                                                  0x583753  /xxxx/springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935
[t=00:00:12.145649][f=-000001] [CrashHandler] Error:   <01>  ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997  CrashHandler::HandleSignal(int, siginfo_t*, void*)
[t=00:00:12.145652][f=-000001] [CrashHandler] Error: [01]                                                                    0x583753  /xxxx/springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997
[t=00:00:12.145656][f=-000001] [CrashHandler] Error:   <02>          /lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7ff1bff62140]  __restore_rt
[t=00:00:12.145669][f=-000001] [CrashHandler] Error:   <02>                                                                   0x14140  ??:?
[t=00:00:12.145673][f=-000001] [CrashHandler] Error:   <03> ./springrts/spring-bar105/rts/ExternalAI/SSkirmishAICallbackImpl.cpp:4326  skirmishAiCallback_WeaponDef_getName
[t=00:00:12.145676][f=-000001] [CrashHandler] Error: [03]                                                                    0x5a5410  /xxxx/springrts/spring-bar105/rts/ExternalAI/SSkirmishAICallbackImpl.cpp:4326
[t=00:00:12.145680][f=-000001] [CrashHandler] Error:   <04>          /ram/bar/AI/Wrappers/Cpp/src-generated/WrappOOAICallback.cpp:507  springai::WrappOOAICallback::GetWeaponDefs()
[t=00:00:12.145683][f=-000001] [CrashHandler] Error: [04]                                                                    0x410f6a  /ram/bar/AI/Wrappers/Cpp/src-generated/WrappOOAICallback.cpp:507
[t=00:00:12.145687][f=-000001] [CrashHandler] Error:   <05>                                  .../include/c++/10/bits/stl_vector.h:919  std::vector<springai::WeaponDef*, std::allocator<springai::WeaponDef*> >::size() const
[t=00:00:12.145691][f=-000001] [CrashHandler] Error:   <05>                                                                   0x89d7a  /usr/include/c++/10/bits/stl_vector.h:919
[t=00:00:12.145695][f=-000001] [CrashHandler] Error:   <05> ./springrts/spring-bar105/AI/Skirmish/BARb/src/circuit/CircuitAI.cpp:1683  circuit::CCircuitAI::InitWeaponDefs()
```

log with jvm
```

[t=00:00:12.125066][f=-000001] [CrashHandler] Error: Segmentation fault in Spring 105.1.1-1-g922607f HEAD
[t=00:00:12.125077][f=-000001] [CrashHandler] Error: Halted Stacktrace for Spring 105.1.1-1-g922607f HEAD (SIGSEGV) using libunwind:
[t=00:00:12.134535][f=-000001] [CrashHandler] Error: This stacktrace indicates a problem with a skirmish AI.
[t=00:00:12.418010][f=-000001] [CrashHandler] Error:   <00>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907  CrashHandler::HaltedStacktrace(siginfo_t*, ucontext_t*, char const*)
[t=00:00:12.418038][f=-000001] [CrashHandler] Error: [00]                                                                           0x5830e4  /xxxx/springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907
[t=00:00:12.418046][f=-000001] [CrashHandler] Error:   <01>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935  CrashHandler::CleanupStacktrace(int)
[t=00:00:12.418053][f=-000001] [CrashHandler] Error:   <01>                                                                         0x583753  /xxxx/springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935
[t=00:00:12.418068][f=-000001] [CrashHandler] Error:   <01>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997  CrashHandler::HandleSignal(int, siginfo_t*, void*)
[t=00:00:12.418075][f=-000001] [CrashHandler] Error: [01]                                                                           0x583753  /xxxx/springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997
[t=00:00:12.418082][f=-000001] [CrashHandler] Error:   <02>                     /opt/jdk-17/lib/server/libjvm.so(+0xcb8949) [0x7f4ca52b8949]  PosixSignals::chained_handler(int, siginfo*, void*) [clone .part.0]
[t=00:00:12.418089][f=-000001] [CrashHandler] Error: [02]                                                                           0xcb8949  ??:?
[t=00:00:12.418096][f=-000001] [CrashHandler] Error:   <03> /opt/jdk-17/lib/server/libjvm.so(JVM_handle_linux_signal+0x256) [0x7f4ca52b93a6]  JVM_handle_linux_signal
[t=00:00:12.418103][f=-000001] [CrashHandler] Error:   <03>                                                                         0xcb93a6  ??:?
[t=00:00:12.418110][f=-000001] [CrashHandler] Error:   <04>                 /lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7f4deb95b140]  __restore_rt
[t=00:00:12.418117][f=-000001] [CrashHandler] Error:   <04>                                                                          0x14140  ??:?
[t=00:00:12.418123][f=-000001] [CrashHandler] Error:   <05>        ./springrts/spring-bar105/rts/ExternalAI/SSkirmishAICallbackImpl.cpp:4326  skirmishAiCallback_WeaponDef_getName
[t=00:00:12.418130][f=-000001] [CrashHandler] Error: [05]                                                                           0x5a5410  /xxxx/springrts/spring-bar105/rts/ExternalAI/SSkirmishAICallbackImpl.cpp:4326
[t=00:00:12.418137][f=-000001] [CrashHandler] Error:   <06>                 /ram/bar/AI/Wrappers/Cpp/src-generated/WrappOOAICallback.cpp:507  springai::WrappOOAICallback::GetWeaponDefs()
[t=00:00:12.418144][f=-000001] [CrashHandler] Error: [06]                                                                           0x410f6a  /ram/bar/AI/Wrappers/Cpp/src-generated/WrappOOAICallback.cpp:507
[t=00:00:12.418151][f=-000001] [CrashHandler] Error:   <07>                                         .../include/c++/10/bits/stl_vector.h:919  std::vector<springai::WeaponDef*, std::allocator<springai::WeaponDef*> >::size() const
[t=00:00:12.418158][f=-000001] [CrashHandler] Error:   <07>                                                                          0x89d7a  /usr/include/c++/10/bits/stl_vector.h:919
[t=00:00:12.418164][f=-000001] [CrashHandler] Error:   <07>        ./springrts/spring-bar105/AI/Skirmish/BARb/src/circuit/CircuitAI.cpp:1683  circuit::CCircuitAI::InitWeaponDefs()
```

**Comment by lhog** [comment]
Try loading it under `gdb` and see if it says something smart in the process.

**Comment by neoedmund** [comment]
```
gdb --args /usr/local/bin/spring --write-dir /home/neoe/.spring  /home/neoe/.spring/script4safe.txt

Thread 1 "spring-main" received signal SIGSEGV, Segmentation fault.
0x00007fbefd60062d in ?? ()
(gdb) bt
#0  0x00007fbefd60062d in ?? ()
#1  0x0000000000200246 in ?? ()
#2  0x00007fbefd600724 in ?? ()
#3  0x00007fbf2860ecd0 in ?? () from /opt/jdk-17/lib/server/libjvm.so
#4  0x00007ffd158cf240 in ?? ()
#5  0x00007fbf282167d9 in VM_Version::get_processor_features() () from /opt/jdk-17/lib/server/libjvm.so

(gdb) c

Thread 1 "spring-main" received signal SIGSEGV, Segmentation fault.
0x00007fc09eda4077 in ?? () from /lib/x86_64-linux-gnu/libc.so.6

(gdb) bt
#0  0x00007fc09eda4077 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000561d38290bee in CSoundSource::PlayStream (this=this@entry=0x7fbf6c05b4a8, channel=channel@entry=0x561d393336a0 <audioChannelMem>, file="music/original/peace/ryan krause - new order.ogg", volume=1)
    at /xxxx/spring-bar105/rts/System/Sound/OpenAL/SoundSource.cpp:293
#2  0x0000561d38282574 in AudioChannel::StreamPlay (this=0x561d393336a0 <audioChannelMem>, filepath="music/original/peace/ryan krause - new order.ogg", volume=<optimized out>, enqueue=<optimized out>)
    at /xxxx/spring-bar105/rts/System/Sound/OpenAL/AudioChannel.cpp:194
#3  0x0000561d37f33cfb in LuaUnsyncedCtrl::PlaySoundStream (L=0x561dbc44bd50) at /usr/include/c++/10/ext/new_allocator.h:89
#4  0x0000561d382b90b0 in luaD_precall (L=L@entry=0x561dbc44bd50, func=0x561dd1dea28c, nresults=nresults@entry=0) at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:320
#5  0x0000561d382c8494 in luaV_execute (L=L@entry=0x561dbc44bd50, nexeccalls=2, nexeccalls@entry=1) at /xxxx/spring-bar105/rts/lib/lua/src/lvm.cpp:620
#6  0x0000561d382b9515 in luaD_call (L=0x561dbc44bd50, L@entry=<error reading variable: value has been optimized out>, func=0x561dd1dea18c, func@entry=<error reading variable: value has been optimized out>,
    nResults=<error reading variable: value has been optimized out>) at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:378
#7  0x0000561d382b8a3e in luaD_rawrunprotected (L=0x561dbc44bd50, f=<optimized out>, ud=<optimized out>) at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:116
#8  0x0000561d382b97f0 in luaD_pcall (L=L@entry=0x561dbc44bd50, func=func@entry=0x561d382b0a00 <f_call(lua_State*, void*)>, u=u@entry=0x7ffd158d10a0, old_top=256, ef=<optimized out>)
    at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:464
#9  0x0000561d382b3065 in lua_pcall (L=L@entry=0x561dbc44bd50, nargs=<optimized out>, nresults=nresults@entry=-1, errfunc=errfunc@entry=0) at /xxxx/spring-bar105/rts/lib/lua/src/lapi.cpp:833
#10 0x0000561d382b5058 in luaB_pcall (L=0x561dbc44bd50) at /xxxx/spring-bar105/rts/lib/lua/src/lbaselib.cpp:377
#11 0x0000561d382b90b0 in luaD_precall (L=L@entry=0x561dbc44bd50, func=0x561dd1dea17c, nresults=nresults@entry=-1) at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:320
#12 0x0000561d382c8494 in luaV_execute (L=L@entry=0x561dbc44bd50, nexeccalls=3, nexeccalls@entry=1) at /xxxx/spring-bar105/rts/lib/lua/src/lvm.cpp:620
#13 0x0000561d382b9515 in luaD_call (L=0x561dbc44bd50, L@entry=<error reading variable: value has been optimized out>, func=0x561dbb655eec, func@entry=<error reading variable: value has been optimized out>,
    nResults=<error reading variable: value has been optimized out>) at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:378
#14 0x0000561d382b8a3e in luaD_rawrunprotected (L=0x561dbc44bd50, f=<optimized out>, ud=<optimized out>) at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:116
#15 0x0000561d382b97f0 in luaD_pcall (L=L@entry=0x561dbc44bd50, func=func@entry=0x561d382b0a00 <f_call(lua_State*, void*)>, u=u@entry=0x7ffd158d1260, old_top=16, ef=<optimized out>)
    at /xxxx/spring-bar105/rts/lib/lua/src/ldo.cpp:464
#16 0x0000561d382b3065 in lua_pcall (L=L@entry=0x561dbc44bd50, nargs=nargs@entry=0, nresults=nresults@entry=0, errfunc=errfunc@entry=0) at /xxxx/spring-bar105/rts/lib/lua/src/lapi.cpp:833
#17 0x0000561d37e765d7 in CLuaHandle::ScopedLuaCall::ScopedLuaCall (_popErrFunc=false, _errFuncIdx=0, _nOutArgs=0, _nInArgs=0, func=0x561d38817960 <CLuaHandle::Update()::cmdStr> "Update", state=0x561dbc44bd50,
    handle=0x561da48e1e00, this=<synthetic pointer>) at /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:327
#18 CLuaHandle::RunCallInTraceback (this=0x561da48e1e00, L=0x561dbc44bd50, hs=<optimized out>, ts=0x7ffd158d1360, inArgs=0, outArgs=0, errFuncIndex=0, popErrorFunc=false)
    at /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:413
#19 0x0000561d37e76c88 in CLuaHandle::RunCallInTraceback (this=0x561da48e1e00, L=0x561dbc44bd50, hs=..., inArgs=<optimized out>, outArgs=<optimized out>, errFuncIndex=<optimized out>, popErrFunc=false)
    at /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:423
#20 0x0000561d37e78411 in CLuaHandle::RunCallIn (outArgs=0, inArgs=0, hs=..., L=<optimized out>, this=0x561da48e1e00) at /xxxx/spring-bar105/rts/Lua/LuaHandle.h:375
#21 CLuaHandle::Update (this=0x561da48e1e00) at /xxxx/spring-bar105/rts/Lua/LuaHandle.cpp:1686
#22 0x0000561d3818dac4 in IterateEventClientList<std::vector<CEventClient*, std::allocator<CEventClient*> >, void (CEventClient::*)()> (list=std::vector of length 3, capacity 4 = {...},
    func=@0x7ffd158d1450: &virtual table offset 744) at /xxxx/spring-bar105/rts/System/EventHandler.cpp:458
#23 0x0000561d38187324 in CEventHandler::Update (this=<optimized out>) at /xxxx/spring-bar105/rts/System/EventHandler.cpp:581
#24 0x0000561d37d29cb9 in CGame::UpdateUnsynced (this=0x561d7cf5e760, currentTime=...) at /xxxx/spring-bar105/rts/Game/Game.cpp:1443
#25 0x0000561d37d2a37c in CGame::Draw (this=0x561d7cf5e760) at /xxxx/spring-bar105/rts/Game/Game.cpp:1464
#26 0x0000561d381b5088 in SpringApp::Update (this=this@entry=0x7ffd158d1a10) at /xxxx/spring-bar105/rts/System/SpringApp.cpp:807
#27 0x0000561d381b82d8 in SpringApp::Run (this=this@entry=0x7ffd158d1a10) at /xxxx/spring-bar105/rts/System/SpringApp.cpp:845
#28 0x0000561d381a2083 in Run (argc=7, argv=0x7ffd158d1b48) at /xxxx/spring-bar105/rts/System/Main.cpp:48
#29 0x00007fc09ec67d0a in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#30 0x0000561d37d05fca in _start () at /usr/include/c++/10/ext/new_allocator.h:89
```

SoundSource.cpp:293
```
	curStream = COggStream(id);
```
The first  `Segmentation fault. VM_Version::get_processor_features() () from /opt/jdk-17/lib/server/libjvm.so` also appears in `if(1)return;` version which runs normally, so might be be ignored.

**Comment by lhog** [comment]
Ok, interesting...

So things to do:
* Fill `COggStream::COggStream(ALuint _source)` with  LOG() calls, just to see where it fails
* Implement explicit copy constructor and copy assignment operator in `COggStream` and stuff it with LOG()'s too.

**Comment by neoedmund** [comment]
> 
>     * Fill `COggStream::COggStream(ALuint _source)` with  LOG() calls, just to see where it fails
source is 
```
COggStream::COggStream(ALuint _source)
	: vorbisInfo(nullptr)
	, source(_source)
	, format(AL_FORMAT_MONO16)
	, stopped(true)
	, paused(false)
{
	memset(buffers, 0, NUM_BUFFERS * sizeof(buffers[0]));
	memset(pcmDecodeBuffer, 0, BUFFER_SIZE * sizeof(pcmDecodeBuffer[0]));
}
```
and .h
```
	static constexpr unsigned int BUFFER_SIZE = 512 * 1024; // 512KB
	static constexpr unsigned int NUM_BUFFERS = 2;
	char pcmDecodeBuffer[BUFFER_SIZE];
	ALuint buffers[NUM_BUFFERS];
```
 don't seem able to brings any troubles.
> 
>     * Implement explicit copy constructor and copy assignment operator in `COggStream` and stuff it with LOG()'s too.
I don't know how to :)

**Comment by lhog** [comment]
Do you know how to compile the spring binary? If so I can drop you some sources.

**Comment by neoedmund** [comment]
Yes, please.

**Comment by lhog** [comment]
[ogg.zip](https://github.com/beyond-all-reason/spring/files/8598917/ogg.zip)

Unzip and `patch -p0 < ogg.patch`, then compile. Hopefully, will do the trick.

**Comment by lhog** [comment]
[ogg.zip](https://github.com/beyond-all-reason/spring/files/8598937/ogg.zip)

Unzip, `patch -p0 < ogg.patch`, compile, use :)

**Comment by neoedmund** [comment]
[debug-infolog.txt](https://github.com/beyond-all-reason/spring/files/8598987/debug-infolog.txt)
wow, seems last `COggStream 2` not show up but error, how can this be?

**Comment by lhog** [comment]
Opsie, can you replace `LOG("%s 1", __func__);` with `LOG("%s 2", __func__);` btw

**Comment by lhog** [comment]
Aha
`An irrecoverable stack overflow has occurred.`

**Comment by neoedmund** [comment]
Okay, there must be a reason and I think I got it.

`char pcmDecodeBuffer[BUFFER_SIZE]; `  takes 512KB on stack, and it's okay something. but in linux and jvm loaded, it triggered to be problematic .

So as a quick fix.

in COggStream.h
```
char* pcmDecodeBuffer; //[BUFFER_SIZE];

	~COggStream() { Stop(); free(pcmDecodeBuffer); }
```
in COggStream.cpp
```
		pcmDecodeBuffer = (char*)  malloc(BUFFER_SIZE);  // +
	memset(pcmDecodeBuffer, 0, BUFFER_SIZE * sizeof(pcmDecodeBuffer[0]));
		LOG("%s 2", __func__);
```
and after test,  it run normally  :)

I'm not writing pretty cpp code so would you make the bugfix commit :)

**Comment by lhog** [comment]
Yep I came to the same conclusion.

Try this one please
[ogg.zip](https://github.com/beyond-all-reason/spring/files/8599056/ogg.zip)

**Comment by neoedmund** [comment]
Your fix works here!  jvm loaded while ogg background music plays, so sweet.

**Comment by lhog** [comment]
Ok let's consider it fixed with the new release of the engine.
Thanks a lot for your inputs!

**Comment by neoedmund** [comment]
wait, hold on.
still crashes on stop(), maybe when 1 ogg finished play.
```
[t=00:06:37.952571][f=0011385] [CrashHandler] Error: Segmentation fault in Spring 105.1.1-934-g75e1875 BAR105
[t=00:06:37.952599][f=0011385] [CrashHandler] Error: Halted Stacktrace for Spring 105.1.1-934-g75e1875 BAR105 (SIGSEGV) using libunwind:
[t=00:06:38.209158][f=0011385] [CrashHandler] Error:   <00>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907  CrashHandler::HaltedStacktrace(siginfo_t*, ucontext_t*, char const*)
[t=00:06:38.209183][f=0011385] [CrashHandler] Error: [00]                                                                           0x695374  /myhome/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:907
[t=00:06:38.209188][f=0011385] [CrashHandler] Error:   <01>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935  CrashHandler::CleanupStacktrace(int)
[t=00:06:38.209192][f=0011385] [CrashHandler] Error:   <01>                                                                         0x6959e3  /myhome/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:935
[t=00:06:38.209197][f=0011385] [CrashHandler] Error:   <01>         ./springrts/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997  CrashHandler::HandleSignal(int, siginfo_t*, void*)
[t=00:06:38.209202][f=0011385] [CrashHandler] Error: [01]                                                                           0x6959e3  /myhome/spring-bar105/rts/System/Platform/Linux/CrashHandler.cpp:997
[t=00:06:38.209206][f=0011385] [CrashHandler] Error:   <02>                     /opt/jdk-17/lib/server/libjvm.so(+0xcb8949) [0x7fbd914b8949]  PosixSignals::chained_handler(int, siginfo*, void*) [clone .part.0]
[t=00:06:38.209211][f=0011385] [CrashHandler] Error: [02]                                                                           0xcb8949  ??:?
[t=00:06:38.209215][f=0011385] [CrashHandler] Error:   <03> /opt/jdk-17/lib/server/libjvm.so(JVM_handle_linux_signal+0x256) [0x7fbd914b93a6]  JVM_handle_linux_signal
[t=00:06:38.209221][f=0011385] [CrashHandler] Error:   <03>                                                                         0xcb93a6  ??:?
[t=00:06:38.209225][f=0011385] [CrashHandler] Error:   <04>                 /lib/x86_64-linux-gnu/libpthread.so.0(+0x14140) [0x7fbf09062140]  __restore_rt
[t=00:06:38.209230][f=0011385] [CrashHandler] Error:   <04>                                                                          0x14140  ??:?
[t=00:06:38.209234][f=0011385] [CrashHandler] Error:   <05> .../ib/x86_64-linux-gnu/libvorbis.so.0(vorbis_block_clear+0x34) [0x7fbf07e212c4]  vorbis_block_clear
[t=00:06:38.209247][f=0011385] [CrashHandler] Error:   <05>                                                                           0x82c4  ??:?
[t=00:06:38.209252][f=0011385] [CrashHandler] Error:   <06>       .../ib/x86_64-linux-gnu/libvorbisfile.so.3(ov_clear+0x1c) [0x7fbf08c08a8c]  ov_clear
[t=00:06:38.209256][f=0011385] [CrashHandler] Error:   <06>                                                                           0x3a8c  ??:?
[t=00:06:38.209261][f=0011385] [CrashHandler] Error:   <07>              ./springrts/spring-bar105/rts/System/Sound/OpenAL/OggStream.cpp:188  COggStream::Stop()
[t=00:06:38.209266][f=0011385] [CrashHandler] Error: [07]                                                                           0x6f2bee  /myhome/spring-bar105/rts/System/Sound/OpenAL/OggStream.cpp:188
[t=00:06:38.209270][f=0011385] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:187  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const
[t=00:06:38.209275][f=0011385] [CrashHandler] Error:   <08>                                                                         0x6f1d72  /usr/include/c++/10/bits/basic_string.h:187
[t=00:06:38.209280][f=0011385] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:222  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
[t=00:06:38.209285][f=0011385] [CrashHandler] Error:   <08>                                                                         0x6f1d72  /usr/include/c++/10/bits/basic_string.h:222
[t=00:06:38.209289][f=0011385] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:231  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
[t=00:06:38.209294][f=0011385] [CrashHandler] Error:   <08>                                                                         0x6f1d72  /usr/include/c++/10/bits/basic_string.h:231
[t=00:06:38.209299][f=0011385] [CrashHandler] Error:   <08>                                       .../include/c++/10/bits/basic_string.h:658  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
[t=00:06:38.209303][f=0011385] [CrashHandler] Error:   <08>                                                                         0x6f1d72  /usr/include/c++/10/bits/basic_string.h:658
[t=00:06:38.209308][f=0011385] [CrashHandler] Error:   <08>                 ./springrts/spring-bar105/rts/System/Sound/OpenAL/OggStream.h:20  COggStream::~COggStream()
[t=00:06:38.209312][f=0011385] [CrashHandler] Error:   <08>                                                                         0x6f1d72  /myhome/spring-bar105/rts/System/Sound/OpenAL/OggStream.h:20
[t=00:06:38.209317][f=0011385] [CrashHandler] Error:   <08>            ./springrts/spring-bar105/rts/System/Sound/OpenAL/SoundSource.cpp:293  CSoundSource::PlayStream(IAudioChannel*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)
[t=00:06:38.209322][f=0011385] [CrashHandler] Error: [08]                                                                           0x6f1d72  /myhome/spring-bar105/rts/System/Sound/OpenAL/SoundSource.cpp:293
[t=00:06:38.209326][f=0011385] [CrashHandler] Error:   <09>           ./springrts/spring-bar105/rts/System/Sound/OpenAL/AudioChannel.cpp:194  AudioChannel::StreamPlay(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, bool)
[t=00:06:38.209331][f=0011385] [CrashHandler] Error: [09]                                                                           0x6e35f4  /myhome/spring-bar105/rts/System/Sound/OpenAL/AudioChannel.cpp:194
[t=00:06:38.209335][f=0011385] [CrashHandler] Error:   <10>                                       .../include/c++/10/bits/basic_string.h:187  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const
[t=00:06:38.209343][f=0011385] [CrashHandler] Error:   <10>                                                                         0x394d7b  /usr/include/c++/10/bits/basic_string.h:187
[t=00:06:38.209347][f=0011385] [CrashHandler] Error:   <10>                                       .../include/c++/10/bits/basic_string.h:222  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
[t=00:06:38.209352][f=0011385] [CrashHandler] Error:   <10>                                                                         0x394d7b  /usr/include/c++/10/bits/basic_string.h:222
[t=00:06:38.209357][f=0011385] [CrashHandler] Error:   <10>                                       .../include/c++/10/bits/basic_string.h:231  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
[t=00:06:38.209361][f=0011385] [CrashHandler] Error:   <10>                                                                         0x394d7b  /usr/include/c++/10/bits/basic_string.h:231
[t=00:06:38.209366][f=0011385] [CrashHandler] Error:   <10>                                       .../include/c++/10/bits/basic_string.h:658  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
[t=00:06:38.209370][f=0011385] [CrashHandler] Error:   <10>                                                                         0x394d7b  /usr/include/c++/10/bits/basic_string.h:658
[t=00:06:38.209375][f=0011385] [CrashHandler] Error:   <10>                        ./springrts/spring-bar105/rts/Lua/LuaUnsyncedCtrl.cpp:600  LuaUnsyncedCtrl::PlaySoundStream(lua_State*)
[t=00:06:38.209380][f=0011385] [CrashHandler] Error: [10]                                                                           0x394d7b  /myhome/spring-bar105/rts/Lua/LuaUnsyncedCtrl.cpp:600

```

```
// stops the currently playing stream
void COggStream::Stop()
{
	if (stopped)
		return;

	ReleaseBuffers();

	msecsPlayed = spring_nulltime;  // <---- line 188
	lastTick = spring_gettime();
```

we need further testing...

**Comment by neoedmund** [comment]
however, my first `malloc/free` code not  crash  after 15 min gaming.

**Comment by neoedmund** [comment]
I have a push in my personal repo https://github.com/neoedmund/spring/commit/c3867844d007ecc679aebe77f45371604dc99101
using malloc/free. It's stable. It's simple, you are free to reference. 
I recommend not using verbose operator overloading, just restrict the usage of the `COggStream` class. and if `malloc` works no need to use `std::vector<char>`. less code less bugs.

**Comment by lhog** [comment]
The problem is we tried new/delete (c++ counterparts to malloc/free) and it still crashes occasionally.
I'm setting up the debug environment to check how and why.

**Comment by neoedmund** [comment]
Okay.
https://stackoverflow.com/a/240308/86600
according to the post
`new/delete` may do something when  low memory.
If you can try `malloc/free`, and if it not crash occasionally, may save you some time. 
The buffer is just memory blocks. `malloc/free`  have more determined behaviors.

**Comment by lhog** [comment]
Can you pull the latest and check if it doesn't crash.

**Comment by neoedmund** [comment]
sure.  I tested over 20 minutes game and no problem. should be okay. I will test more in a few days maybe, if you are not in a hurry. :)

**Comment by lhog** [comment]
Absolutely not in the hurry.
Thanks!

**Comment by neoedmund** [comment]
should be no problem at this time. Thank you for the bugfix.
