### ISSUE TITLE
reflection map faces are still messy (left is right)

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#7]
![screen02067](https://user-images.githubusercontent.com/1476261/107131294-28ba5900-68e6-11eb-8b19-2057c6bd966b.png)

Should be something like that: https://cdn.discordapp.com/attachments/724924957074915358/807656801561608222/unknown.png

**Comment by marcushutchings** [comment]
This has seen no updates for a year. Is it still an issue?

**Comment by icexuick** [comment]
I believe this was fixed, but @Beherith or @lhog can verify

**Comment by lhog** [comment]
Still wrong. My 3D imagination has not been sufficient to wrap them in a correct way

**Comment by lhog** [comment]
Redone in https://github.com/beyond-all-reason/spring/commit/5ac169b774838cab5f69764128fcabc166e8244b

Probably fixed:
![screen00019](https://user-images.githubusercontent.com/1476261/183893004-8ca7b2cb-8d21-45d0-a4d0-e692273fd897.jpg)
.
